name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
          
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm run test
          
      - name: Run Backend Tests
        run: |
          cd backend
          npm run test
          
      - name: Lint Frontend
        run: |
          cd frontend
          npm run lint
          
      - name: Lint Backend
        run: |
          cd backend
          npm run lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd frontend && npm install
          cd ../backend && npm install
          
      - name: Build Frontend
        run: |
          cd frontend
          npm run build
          
      - name: Build Backend
        run: |
          cd backend
          npm run build
          
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/aisoc
            git pull origin master
            cd frontend && npm install && npm run build
            cd ../backend && npm install && npm run build
            pm2 restart all 